[metrics.binary-size.unit]
scale = "binary"
suffix = "B"

# max increase size of 10%
[[metrics.binary-size.rules]]
type = "max-increase"
ratio = 0.1

# max size of 10MB
[[metrics.binary-size.rules]]
type = "max"
value = 10485760.0
