version: 2

workflows:
  version: 2
  workflow:
    jobs:
      - lint
      - test
      - bench

jobs:
  lint:
    docker:
      - image: jdrouet/rust-nightly:buster-slim-dev
    steps:
      - checkout
      - run: rustfmt --check src/{**/,}*.rs

  test:
    machine: true
    steps:
      - checkout
      - run: docker run --env BASIC_DIFF=true --security-opt seccomp=unconfined --volume "${PWD}:/volume" xd009642/tarpaulin cargo tarpaulin --ciserver circle-ci --coveralls $CODECOV_TOKEN --out Lcov
      - run: bash <(curl -s https://codecov.io/bash) -f lcov.info

  bench:
    docker:
      - image: jdrouet/rust-nightly:buster-slim-dev
    steps:
      - checkout
      - restore_cache:
          keys: bench-master
      - run: cargo bench
      - save_cache:
          key: "bench-{{ .Branch }}"
          paths:
            - target/criterion
