[package]
name = "mrml"
description = "Rust implementation of MJML renderer"
keywords = ["email", "mjml"]
version = "0.4.0"
authors = ["Jérémie Drouet <jeremie.drouet@gmail.com>"]
license-file = "license.md"
edition = "2018"
readme = "readme.md"

include = ["src/*", "Cargo.toml"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[badges]
codecov = { repository = "jdrouet/mrml", branch = "main" }
travis-ci = { repository = "jdrouet/mrml", branch = "main" }

[dependencies]
lazy_static = "1.4"
log = "0.4"
rand = { default-features = false, features = ["std"], version = "0.7" }
regex = "1"
xmlparser = "0.13"

[dev-dependencies]
criterion = "0.3"
difference = "2.0"
html_parser = "0.6.2"
test-generator = "0.3.0"

[[bench]]
name = "basic"
path = "benches/basic.rs"
harness = false

[[bench]]
name = "template"
path = "benches/template.rs"
harness = false
