[package]
name = "mrml-core"
version = "0.1.0"
authors = ["Jérémie Drouet <jeremie.drouet@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xmlparser = "0.13"

[dev-dependencies]
html_parser = "0.6.2"
