name: common

on:
  merge_group:
    types: [checks_requested]
  workflow_call:
  pull_request:
  push:
    branches:
      - main

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  code-checking:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-code-checking
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt,clippy
      - uses: ./.github/actions/cargo-cache
        with:
          name: code-checking

      - name: run lint
        run: cargo fmt --all --check

      - name: run check
        run: cargo check --all-features --tests --workspace

      - name: run clippy
        run: cargo clippy --all-targets --all-features --tests --workspace
